server:
  port: 8090
spring:
  application:
    name: LOANS-SERVICE
  datasource:
    url: jdbc:h2:mem:loans-db
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


