server:
  port: 9000
spring:
  application:
    name: CARDS-SERVICE
  datasource:
    url: jdbc:h2:mem:cards-db
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
