server:
  port: 8080
spring:
  application:
    name: ACCOUNTS-SERVICE
  datasource:
    url: jdbc:h2:mem:accounts-db
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
